version: "3"
networks:
    laravel:
services: 
    site:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/:/etc/nginx/conf.d/:rw
        
        depends_on: 
            - php
            - database

        networks:
            - laravel

    php:
        build:
            context: ./
            dockerfile: php.dockerfile
        container_name: php
        volumes: 
            - ./:/var/www/html
        ports: 
            - 9000:9000
        networks: 
            - laravel
    composer:
        image: composer:latest
        entrypoint: composer install
        container_name: composer
        volumes: 
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on: 
            - php
        networks: 
            - laravel
    database:
        image: mariadb:latest
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: "12345"
            MYSQL_DATABASE: "notas"
        ports: 
            - 3306:3306
        networks: 
            - laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST: database
            PMA_PORT: "3306"
            PMA_PASSWORD: "12345"

            MYSQL_ROOT_PASSWORD: "12345"
        ports: 
            - 8080:80
        depends_on: 
            - database
            - php
        networks: 
            - laravel
